name: enough_mail_icalendar
description: iCalendar support for email / mime. Compatible with iCalendar
  Message-Based Interoperability Protocol (iMIP) RFC 6047.
version: 1.0.0
publish_to: 'none'
homepage: https://github.com/rascal-3/enough_mail_icalendar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.17.0
  enough_icalendar: ^0.13.0
  # enough_mail: ^2.1.0
  enough_mail:
    git:
      url: https://github.com/rascal-3/enough_mail.git
      ref: main

dependency_overrides:
  # enough_mail:
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail.git
  #   #path: ../enough_mail
  enough_icalendar:
    git:
      url: https://github.com/Enough-Software/enough_icalendar.git
    #path: ../enough_icalendar

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
